# Generated by Django 5.0.1 on 2024-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_names',
            new_name='products',
        ),
    ]
