# Generated by Django 5.0.1 on 2024-03-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_names_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product_names',
        ),
    ]
