# Generated by Django 5.0.1 on 2024-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_products_order_product_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
