# Generated by Django 5.0.1 on 2024-03-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_product_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
