# Generated by Django 5.0.1 on 2024-03-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
    ]
